spring.application.name=storageManagement

db.url=jdbc:postgresql://localhost:5432/ship_data_hub
db.user=marisight
db.password=marisight123!@#

storage.disk.path=/data/device
storage.threshold1=60.0
storage.threshold2=80.0
storage.batchsize=1000

# 1min
#storage.check-cron=0 */1 * * * *
# 1day 00:00:00
storage.check-cron=0 0 0 * * *

storage.default-retention-days=180
storage.schema=onboard
